### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by d668** [digital-engineering/airbnb-scraper#5]
scrapy crawl bnb -a query="Mezmay, RU" -o MezmayRussia.csv

scrapy crawl bnb -a query="Mezmay, Russia" -o MezmayRussia.csv

scrapy crawl bnb -a query="Mezmay, Krasnodar Krai, Russia" -o MezmayRussia.csv

all bring me anything but listings in Mezmay, Krasnodar Krai, Russia, how come?

**Comment by d668** [comment]
I run this 
```
scrapy crawl bnb \
    -a query="Adeje, Santa Cruz de Tenerife,Spain" \
    -a max_price=81 \
    -a min_price=20 \
    -o out.xlsx
```
And it is running for two hours already. Man I wish it was more user friendly

**Comment by digitalengineering** [comment]
> all bring me anything but listings in Mezmay, Krasnodar Krai, Russia, how come?

Thanks for bringing this to my attention. It looks like Airbnb has updated their backend API to v3, while this project is still using v2. Seems like the v2 api is serving old / incomplete data. Unfortunately it's not something that can be fixed quickly, but I plan to upgrade the project eventually.

> And it is running for two hours already. Man I wish it was more user friendly

The crawler crawls slowly by default, so that Airbnb doesn't block you. It can be adjusted using the `AUTOTHROTTLE_` settings in `settings.py`. More info here: https://docs.scrapy.org/en/latest/topics/autothrottle.html

**Comment by d668** [comment]
It didn't find anything for Adeje, Santa Cruz de Tenerife,Spain either, so it would be awesome if you have a look at it. I think this project is awesome btw if it works

**Comment by d668** [comment]
nothing?

**Comment by digitalengineering** [comment]
@d668 FYI, have updated to use new Airbnb api v3, it should work better now. It looks like the old v2 api wasn't providing up-to-date results anymore.
